CREATE TABLE Persona (
	persona_id SERIAL PRIMARY KEY,
    PERIODO VARCHAR(10),
    TIPO_DNI VARCHAR(10),
    COD_DANE INTEGER,
    FECHA_NACIMIENTO VARCHAR(30),
    EDAD INTEGER,
    GRUPO_ETARIO VARCHAR(20),
    VINCULACION VARCHAR(20),
    GENERO CHAR(1),
    ESTRATO INTEGER,
    SNIES INTEGER,
    LUGAR VARCHAR(100),
    TIPO VARCHAR(20),
    LONGITUD FLOAT,
    LATITUD FLOAT,
    POB_VULNERABLE VARCHAR(100)
   );
   
CREATE TABLE Municipio (
	persona_id SERIAL PRIMARY KEY,
    COD_DANE INTEGER,
    MUNICIPIO_ORIGEN VARCHAR(50)
   );


CREATE TABLE Programa (
	persona_id SERIAL PRIMARY KEY,
    SNIES INTEGER,
    PLAN_ESTUDIOS VARCHAR(100),
    PROGRAMA_ACADEMICO VARCHAR(100),
    FACULTAD VARCHAR(100)
   );


-- Cargar datos en la tabla "Persona"
COPY Persona (PERIODO, TIPO_DNI, COD_DANE, FECHA_NACIMIENTO, EDAD, GRUPO_ETARIO, VINCULACION, GENERO, ESTRATO, SNIES, LUGAR, TIPO, LONGITUD, LATITUD, POB_VULNERABLE)
FROM 'D:\Descargas\Estudiantes_Persona.csv' DELIMITER ';' CSV HEADER;

COPY Municipio (COD_DANE, MUNICIPIO_ORIGEN)
FROM 'D:\Descargas\Estudiantes_Municipio.csv' DELIMITER ';' CSV HEADER;

-- Cargar datos en la tabla "Programa"
COPY Programa (SNIES, PLAN_ESTUDIOS, PROGRAMA_ACADEMICO, FACULTAD)
FROM 'D:\Descargas\Estudiantes_Programa.csv' DELIMITER ';' CSV HEADER;

select * from Persona

select * from Municipio

select * from Programa